//-------------------------------------------------------------------------------------------------------------------------------------------------
// Generated by Make me a Makefile (https://github.com/Orion-CanSat/Make-me-a-Makefile)
//
// Board:            Teensy 4.1
// CPU Speed:        600000000
// Optimization:     -O3
// 
// Time of creation: 2021/03/04 12:00
//-------------------------------------------------------------------------------------------------------------------------------------------------

#ifndef __ORION_DEBUG_H__
#define __ORION_DEBUG_H__

#ifdef _DEBUG
    #define DEBUG(...)                      \
    {                                       \
        if (Serial)                         \
            Serial.println(__VA_ARGS__);    \
        if (logFile)                        \
        {                                   \
            logFile.print("Debug: ");       \
            logFile.println(__VA_ARGS__);   \
        }                                   \
    }
#else
    #define DEBUG(...) { }
#endif

#endif//__ORION_DEBUG_H__